#!/bin/sh
#uname -snrvm
#
# Text Color Variables http://misc.flogisoft.com/bash/tip_colors_and_formatting
tcLtG="\033[00;37m"    # LIGHT GRAY
tcDkG="\033[01;30m"    # DARK GRAY
tcLtR="\033[01;31m"    # LIGHT RED
tcLtGRN="\033[01;32m"  # LIGHT GREEN
tcLtBL="\033[01;34m"   # LIGHT BLUE
tcLtP="\033[01;35m"    # LIGHT PURPLE
tcLtC="\033[01;36m"    # LIGHT CYAN
tcW="\033[01;37m"      # WHITE
tcRESET="\033[0m"
tcORANGE="\033[38;5;209m"
#
# Time of day
HOUR=$(date +"%H")
if [ $HOUR -lt 12  -a $HOUR -ge 0 ]; then TIME="morning"
elif [ $HOUR -lt 17 -a $HOUR -ge 12 ]; then TIME="afternoon"
else TIME="evening"
fi
#
# System uptime
uptime=`cat /proc/uptime | cut -f1 -d.`
upDays=$((uptime/60/60/24))
upHours=$((uptime/60/60%24))
upMins=$((uptime/60%60))
#
# System + Memory
SYS_LOADS=`cat /proc/loadavg | awk '{print $1}'`
MEMORY_USED=`free -b | grep Mem | awk '{print $3/$2 * 100.0}'`
SWAP_USED=`free -b | grep Swap | awk '{print $3/$2 * 100.0}'`
NUM_PROCS=`ps aux | wc -l`
IPADDRESS=`hostname --all-ip-addresses`
#
echo $tcLtG "================================================================="
echo $tcLtG " Good $TIME !                                   $tcORANGE by WhiteK0T."
echo "\e[39m================================================================="
echo $tcLtGRN " - Server Date/Time  :$tcLtBL `date '+%a %d %b %Y / %X %Z'`"
echo $tcLtGRN " - Hostname          :$tcLtBL `hostname -f`"
echo $tcLtGRN " - IP Address        :$tcLtBL $IPADDRESS"
echo $tcLtGRN " - OS Release        :$tcLtBL $(lsb_release -s -d)[$(cat /etc/debian_version)]"
echo $tcLtGRN " - Kernel Release    :$tcLtBL `uname -r` "
echo $tcLtGRN " - Kernel Version    :$tcLtBL `uname -v | cut -d' ' -f4-5` "
echo $tcLtGRN " - CPU Cores/Threads :$tcLtBL `grep -c '^processor' /proc/cpuinfo 2>/dev/null | awk '{cores=\$1} END {print cores \" / \" cores}'`"
echo $tcLtGRN " - Users             :$tcLtBL Currently `users | wc -w` user(s) logged on"
echo $tcLtGRN " - System load       :$tcLtBL $SYS_LOADS / $NUM_PROCS processes running"
echo $tcLtGRN " - Memory used %     :$tcLtBL $MEMORY_USED"
echo $tcLtGRN " - Swap used %       :$tcLtBL $SWAP_USED"
echo $tcLtGRN " - System uptime     :$tcLtBL $upDays days $upHours hours $upMins minutes"
echo $tcLtG "================================================================="
echo $tcRESET ""